# ASP.NET Core

# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
jobs:
- job: buildandtest
  pool:
    vmImage: ubuntu-latest
 
  steps:
  # publish an artifact called drop
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)' 
      artifactName: drop
  
  # deploy to Azure Web App staging
  - task: AzureWebApp@1
    inputs:
      azureSubscription: 'Microsoft Azure Enterprise OL Dev(08339a29-3709-4f55-b71a-d3b34c89fe5a)'
      appType: 'webAppLinux'
      appName: 'my-app-dotnet-win2'
      deployToSlotOrASE: true
      resourceGroupName: 'myapp-rg'
      slotName: 'staging'
      package: '$(Build.ArtifactStagingDirectory)/**/*.zip'



